/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSynologyConfigRouteImport } from './routes/_authenticated/synology-config'
import { Route as AuthenticatedSynologyRouteImport } from './routes/_authenticated/synology'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedGatewaysRouteImport } from './routes/_authenticated/gateways'
import { Route as AuthenticatedGatewayDiagnosticRouteImport } from './routes/_authenticated/gateway-diagnostic'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as ApiPublicGatewayStatusRouteImport } from './routes/api/public/gateway/status'
import { Route as ApiPublicGatewayJobsRouteImport } from './routes/api/public/gateway/jobs'
import { Route as ApiPublicGatewayHeartbeatRouteImport } from './routes/api/public/gateway/heartbeat'
import { Route as ApiPublicGatewayJobsIdStartRouteImport } from './routes/api/public/gateway/jobs.$id.start'
import { Route as ApiPublicGatewayJobsIdFailRouteImport } from './routes/api/public/gateway/jobs.$id.fail'
import { Route as ApiPublicGatewayJobsIdCompleteRouteImport } from './routes/api/public/gateway/jobs.$id.complete'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSynologyConfigRoute =
  AuthenticatedSynologyConfigRouteImport.update({
    id: '/synology-config',
    path: '/synology-config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSynologyRoute = AuthenticatedSynologyRouteImport.update({
  id: '/synology',
  path: '/synology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGatewaysRoute = AuthenticatedGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGatewayDiagnosticRoute =
  AuthenticatedGatewayDiagnosticRouteImport.update({
    id: '/gateway-diagnostic',
    path: '/gateway-diagnostic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const ApiPublicGatewayStatusRoute = ApiPublicGatewayStatusRouteImport.update({
  id: '/api/public/gateway/status',
  path: '/api/public/gateway/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGatewayJobsRoute = ApiPublicGatewayJobsRouteImport.update({
  id: '/api/public/gateway/jobs',
  path: '/api/public/gateway/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGatewayHeartbeatRoute =
  ApiPublicGatewayHeartbeatRouteImport.update({
    id: '/api/public/gateway/heartbeat',
    path: '/api/public/gateway/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGatewayJobsIdStartRoute =
  ApiPublicGatewayJobsIdStartRouteImport.update({
    id: '/$id/start',
    path: '/$id/start',
    getParentRoute: () => ApiPublicGatewayJobsRoute,
  } as any)
const ApiPublicGatewayJobsIdFailRoute =
  ApiPublicGatewayJobsIdFailRouteImport.update({
    id: '/$id/fail',
    path: '/$id/fail',
    getParentRoute: () => ApiPublicGatewayJobsRoute,
  } as any)
const ApiPublicGatewayJobsIdCompleteRoute =
  ApiPublicGatewayJobsIdCompleteRouteImport.update({
    id: '/$id/complete',
    path: '/$id/complete',
    getParentRoute: () => ApiPublicGatewayJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/gateway-diagnostic': typeof AuthenticatedGatewayDiagnosticRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/synology': typeof AuthenticatedSynologyRoute
  '/synology-config': typeof AuthenticatedSynologyConfigRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/gateway/heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/gateway/jobs': typeof ApiPublicGatewayJobsRouteWithChildren
  '/api/public/gateway/status': typeof ApiPublicGatewayStatusRoute
  '/api/public/gateway/jobs/$id/complete': typeof ApiPublicGatewayJobsIdCompleteRoute
  '/api/public/gateway/jobs/$id/fail': typeof ApiPublicGatewayJobsIdFailRoute
  '/api/public/gateway/jobs/$id/start': typeof ApiPublicGatewayJobsIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/gateway-diagnostic': typeof AuthenticatedGatewayDiagnosticRoute
  '/gateways': typeof AuthenticatedGatewaysRoute
  '/synology': typeof AuthenticatedSynologyRoute
  '/synology-config': typeof AuthenticatedSynologyConfigRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/gateway/heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/gateway/jobs': typeof ApiPublicGatewayJobsRouteWithChildren
  '/api/public/gateway/status': typeof ApiPublicGatewayStatusRoute
  '/api/public/gateway/jobs/$id/complete': typeof ApiPublicGatewayJobsIdCompleteRoute
  '/api/public/gateway/jobs/$id/fail': typeof ApiPublicGatewayJobsIdFailRoute
  '/api/public/gateway/jobs/$id/start': typeof ApiPublicGatewayJobsIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/gateway-diagnostic': typeof AuthenticatedGatewayDiagnosticRoute
  '/_authenticated/gateways': typeof AuthenticatedGatewaysRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/synology': typeof AuthenticatedSynologyRoute
  '/_authenticated/synology-config': typeof AuthenticatedSynologyConfigRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/gateway/heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/gateway/jobs': typeof ApiPublicGatewayJobsRouteWithChildren
  '/api/public/gateway/status': typeof ApiPublicGatewayStatusRoute
  '/api/public/gateway/jobs/$id/complete': typeof ApiPublicGatewayJobsIdCompleteRoute
  '/api/public/gateway/jobs/$id/fail': typeof ApiPublicGatewayJobsIdFailRoute
  '/api/public/gateway/jobs/$id/start': typeof ApiPublicGatewayJobsIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/gateway-diagnostic'
    | '/gateways'
    | '/projects'
    | '/synology'
    | '/synology-config'
    | '/tasks'
    | '/users'
    | '/projects/$id'
    | '/projects/'
    | '/api/public/gateway/heartbeat'
    | '/api/public/gateway/jobs'
    | '/api/public/gateway/status'
    | '/api/public/gateway/jobs/$id/complete'
    | '/api/public/gateway/jobs/$id/fail'
    | '/api/public/gateway/jobs/$id/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/gateway-diagnostic'
    | '/gateways'
    | '/synology'
    | '/synology-config'
    | '/tasks'
    | '/users'
    | '/projects/$id'
    | '/projects'
    | '/api/public/gateway/heartbeat'
    | '/api/public/gateway/jobs'
    | '/api/public/gateway/status'
    | '/api/public/gateway/jobs/$id/complete'
    | '/api/public/gateway/jobs/$id/fail'
    | '/api/public/gateway/jobs/$id/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/gateway-diagnostic'
    | '/_authenticated/gateways'
    | '/_authenticated/projects'
    | '/_authenticated/synology'
    | '/_authenticated/synology-config'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/'
    | '/api/public/gateway/heartbeat'
    | '/api/public/gateway/jobs'
    | '/api/public/gateway/status'
    | '/api/public/gateway/jobs/$id/complete'
    | '/api/public/gateway/jobs/$id/fail'
    | '/api/public/gateway/jobs/$id/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicGatewayHeartbeatRoute: typeof ApiPublicGatewayHeartbeatRoute
  ApiPublicGatewayJobsRoute: typeof ApiPublicGatewayJobsRouteWithChildren
  ApiPublicGatewayStatusRoute: typeof ApiPublicGatewayStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/synology-config': {
      id: '/_authenticated/synology-config'
      path: '/synology-config'
      fullPath: '/synology-config'
      preLoaderRoute: typeof AuthenticatedSynologyConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/synology': {
      id: '/_authenticated/synology'
      path: '/synology'
      fullPath: '/synology'
      preLoaderRoute: typeof AuthenticatedSynologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gateways': {
      id: '/_authenticated/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof AuthenticatedGatewaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gateway-diagnostic': {
      id: '/_authenticated/gateway-diagnostic'
      path: '/gateway-diagnostic'
      fullPath: '/gateway-diagnostic'
      preLoaderRoute: typeof AuthenticatedGatewayDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/api/public/gateway/status': {
      id: '/api/public/gateway/status'
      path: '/api/public/gateway/status'
      fullPath: '/api/public/gateway/status'
      preLoaderRoute: typeof ApiPublicGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gateway/jobs': {
      id: '/api/public/gateway/jobs'
      path: '/api/public/gateway/jobs'
      fullPath: '/api/public/gateway/jobs'
      preLoaderRoute: typeof ApiPublicGatewayJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gateway/heartbeat': {
      id: '/api/public/gateway/heartbeat'
      path: '/api/public/gateway/heartbeat'
      fullPath: '/api/public/gateway/heartbeat'
      preLoaderRoute: typeof ApiPublicGatewayHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gateway/jobs/$id/start': {
      id: '/api/public/gateway/jobs/$id/start'
      path: '/$id/start'
      fullPath: '/api/public/gateway/jobs/$id/start'
      preLoaderRoute: typeof ApiPublicGatewayJobsIdStartRouteImport
      parentRoute: typeof ApiPublicGatewayJobsRoute
    }
    '/api/public/gateway/jobs/$id/fail': {
      id: '/api/public/gateway/jobs/$id/fail'
      path: '/$id/fail'
      fullPath: '/api/public/gateway/jobs/$id/fail'
      preLoaderRoute: typeof ApiPublicGatewayJobsIdFailRouteImport
      parentRoute: typeof ApiPublicGatewayJobsRoute
    }
    '/api/public/gateway/jobs/$id/complete': {
      id: '/api/public/gateway/jobs/$id/complete'
      path: '/$id/complete'
      fullPath: '/api/public/gateway/jobs/$id/complete'
      preLoaderRoute: typeof ApiPublicGatewayJobsIdCompleteRouteImport
      parentRoute: typeof ApiPublicGatewayJobsRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedGatewayDiagnosticRoute: typeof AuthenticatedGatewayDiagnosticRoute
  AuthenticatedGatewaysRoute: typeof AuthenticatedGatewaysRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSynologyRoute: typeof AuthenticatedSynologyRoute
  AuthenticatedSynologyConfigRoute: typeof AuthenticatedSynologyConfigRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedGatewayDiagnosticRoute: AuthenticatedGatewayDiagnosticRoute,
  AuthenticatedGatewaysRoute: AuthenticatedGatewaysRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSynologyRoute: AuthenticatedSynologyRoute,
  AuthenticatedSynologyConfigRoute: AuthenticatedSynologyConfigRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicGatewayJobsRouteChildren {
  ApiPublicGatewayJobsIdCompleteRoute: typeof ApiPublicGatewayJobsIdCompleteRoute
  ApiPublicGatewayJobsIdFailRoute: typeof ApiPublicGatewayJobsIdFailRoute
  ApiPublicGatewayJobsIdStartRoute: typeof ApiPublicGatewayJobsIdStartRoute
}

const ApiPublicGatewayJobsRouteChildren: ApiPublicGatewayJobsRouteChildren = {
  ApiPublicGatewayJobsIdCompleteRoute: ApiPublicGatewayJobsIdCompleteRoute,
  ApiPublicGatewayJobsIdFailRoute: ApiPublicGatewayJobsIdFailRoute,
  ApiPublicGatewayJobsIdStartRoute: ApiPublicGatewayJobsIdStartRoute,
}

const ApiPublicGatewayJobsRouteWithChildren =
  ApiPublicGatewayJobsRoute._addFileChildren(ApiPublicGatewayJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicGatewayHeartbeatRoute: ApiPublicGatewayHeartbeatRoute,
  ApiPublicGatewayJobsRoute: ApiPublicGatewayJobsRouteWithChildren,
  ApiPublicGatewayStatusRoute: ApiPublicGatewayStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
